create table
  public.global_inventory (
    id bigint generated by default as identity,
    gold integer not null default 100,
    num_red_ml integer not null default 0,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint g_i_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    customer_name text not null,
    payment text null,
    created_at timestamp with time zone not null default now(),
    fulfilled boolean not null default false,
    constraint carts_n_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_item (
    cart_id bigint not null,
    item_id bigint not null,
    quantity integer not null default 0,
    constraint cart_item_pkey primary key (cart_id, item_id),
    constraint cart_item_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_item_item_id_fkey foreign key (item_id) references catalog_item (id)
  ) tablespace pg_default;

create table
  public.catalog_item (
    id bigint generated by default as identity,
    sku text not null,
    name text not null,
    price integer not null default 0,
    potion_type integer[] not null default '{0,0,0,0}'::integer[],
    quantity integer not null default 0,
    constraint catalog_item_pkey primary key (id),
    constraint potion_type_sum check (
      (array_length(potion_type, 1) = 4)
    )
  ) tablespace pg_default;